packages:
  - packages/*

ignoredBuiltDependencies:
  - sharp

injectWorkspacePackages: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - '@studiocms/*'
  - '@withstudiocms/*'

syncInjectedDepsAfterScripts:
  - build
