name: Deploy Dokploy Compose
description: Update and deploy a Dokploy Compose deployment

inputs:
  api_url:
    description: "The Dokploy API URL"
    required: true
    default: "https://api.dokploy.com/v1"
  api_key:
    description: "The Dokploy API key"
    required: true
  compose_id:
    description: "The Dokploy Compose ID to update and deploy"
    required: true
  image:
    description: "The Docker image to set in the Compose file"
    required: true

outputs:
  domain:
    description: "The domain of the deployed Compose"
    value: ${{ steps.update-and-deploy.outputs.domain }}

runs:
  using: "composite"
  steps:
    - name: Update compose and deploy
      id: update-and-deploy
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.api_url }}"
        echo "::add-mask::${{ inputs.api_key }}"
        echo "::add-mask::${{ inputs.compose_id }}"

        echo "Updating compose and triggering deploy..."

        # Captures the HTTP status code and discards the body
        update_response_code=$(curl -sS -o /dev/null -w "%{http_code}" -X 'POST' "${{ inputs.api_url }}/compose.update" -H 'accept: application/json' -H 'Content-Type: application/json' -H "x-api-key: ${{ inputs.api_key }}" -d '{
          "composeId": "'${{ inputs.compose_id }}'",
          "composeFile": "services:\n  app:\n    image: '${{ inputs.image }}'\n    restart: always\n    env_file:\n      - .env"
        }')

        echo "update_status_code=$update_response_code" >> $GITHUB_OUTPUT

        deploy_response_code=$(curl -sS -o /dev/null -w "%{http_code}" -X 'POST' "${{ inputs.api_url }}/compose.deploy" -H 'accept: application/json' -H 'Content-Type: application/json' -H "x-api-key: ${{ inputs.api_key }}" -d '{
          "composeId": "'${{ inputs.compose_id }}'",
          "title": "Deploy from CI",
          "description": "Deploying the latest changes from the CI pipeline. image: '${{ inputs.image }}'"
        }')

        echo "deploy_status_code=$deploy_response_code" >> $GITHUB_OUTPUT

        echo "Compose updated and deploy triggered."
